mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/01\ Pop\ Goes\ The\ Weasel\ \(Radio\ Edit\)*.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/02\ Pop\ Goes\ The\ Weasel\ \(LP\ Version\)*.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/03\ Pop\ Goes\ The\ Weasel\ \(Instrumental\)*.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/3rd\ Bass/Pop\ Goes\ The\ Weasel/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/01\ Nutshell.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/02\ Brother.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/03\ No\ Excuses.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/04\ Sludge\ Factory.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/05\ Down\ in\ a\ Hole.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/06\ Angry\ Chair.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/07\ Rooster.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/08\ Got\ Me\ Wrong.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/09\ Heaven\ Beside\ You.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/10\ Would*.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/11\ Frogs.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/12\ Over\ Now.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/Alice\ In\ Chains/Unplugged/13\ Killer\ is\ Me.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Alice\ In\ Chains/Unplugged/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/01\ Twin\ Peaks\ Theme.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/02\ Laura\ Palmer\'s\ Theme.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/03\ Audrey\'s\ Dance.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/04\ The\ Nightingale.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/05\ Freshly\ Squeezed.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/06\ The\ Bookhouse\ Boys.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/07\ Into\ The\ Night.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/08\ Night\ Life\ In\ Twin\ Peaks.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/09\ Dance\ Of\ The\ Dream\ Man.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/10\ Love\ Theme\ From\ Twin\ Peaks.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/11\ Falling.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Angelo\ Badalamenti/Twin\ Peaks\ Soundtrack/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/01\ Little\ Plastic\ Castle.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/02\ Fuel.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/03\ Gravel.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/04\ As\ Is.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/05\ Two\ Little\ Girls.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/06\ Deep\ Dish.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/07\ Loom.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/08\ Pixie.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/09\ Swan\ Dive.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/10\ Glass\ House.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/11\ Independence\ Day.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Little\ Plastic\ Castle/12\ Pulse.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Little\ Plastic\ Castle/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/01\ buildings\ and\ bridges.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/02\ out\ of\ range\ \(acoustic\).mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/03\ letter\ to\ a\ john.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/04\ hell\ yeah.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/05\ how\ have\ you\ been.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/06\ overlap.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/07\ face\ up\ and\ sing.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/08\ falling\ is\ like\ this.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/09\ out\ of\ range\ \(electric\).mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/10\ you\ had\ time.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/11\ if\ he\ tries\ anything.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Out\ of\ Range/12\ the\ diner.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Out\ of\ Range/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/01\ your\ next\ bold\ move.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/02\ this\ box\ contains....mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/03\ reckoning.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/04\ so\ what.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/05\ prison\ prism.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/06\ imagine\ that.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/07\ flood\ waters.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/08\ grey.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/09\ subdivision.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/10\ old\ old\ song.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/11\ sick\ of\ me.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/12\ don\'t\ nobody\ know.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/13\ school\ night.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/14\ that\ was\ my\ love.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/15\ revelling.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Reckoning/16\ in\ here.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Reckoning/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/01\ ain\'t\ that\ the\ way.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/02\ o.k..mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/03\ garden\ of\ simple.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/04\ tamburitza\ lingua.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/05\ marrow.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/06\ heartbreak\ even.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/07\ harvest.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/08\ kazoointoit.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/09\ whatall\ is\ nice.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/10\ what\ how\ when\ where\ \(why\ who\).mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/11\ fierce\ flawless.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/12\ rock\ paper\ scissors.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Revelling/13\ beautiful\ night.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Revelling/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Swing\ Set/01\ Swing\ \(radio\ set\).mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Swing\ Set/02\ Swing\ \(album\ version\).mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Swing\ Set/03\ To\ The\ Teeth\ \(shoot-out\ remix\).mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Swing\ Set/04\ Do\ Re\ Mi.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Swing\ Set/05\ When\ I\'m\ Gone.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Ani\ DiFranco/Swing\ Set/06\ Hurricane.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/Ani\ DiFranco/Swing\ Set/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/01\ Joe\ Hill\ \(instrumental\).mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/02\ Stupid\'s\ Song.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/03\ The\ Most\ Dangerous\ Woman.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/04\ Stupid\'s\ Pledge.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/05\ Direct\ Action.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/06\ Pie\ In\ The\ Sky.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/07\ Shoot\ Or\ Stab\ Them.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/08\ Lawrence.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/09\ Bread\ And\ Roses.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/10\ Why\ Come*.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/11\ Unless\ You\ Are\ Free.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/12\ I\ Will\ Not\ Obey.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/13\ The\ Long\ Memory.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
mkdir -pv -m 0700 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/ ; mv -nv /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/14\ The\ Silence\ That\ Is\ Me.mp3 /Volumes/share/terryn/My\ Documents/My\ Music/iTunes/iTunes\ Music/Music/ani\ difranco\ and\ utah\ phillips/Fellow\ Workers/
